#!/bin/bash

# Install wrapper for RISC OS, to handle ",ff8" extensions

installparams=
dest=

if [ "$1" == "cp" ] ; then
  command=/bin/cp
  shift
else
  command=/usr/bin/install
fi

for param in $@ ; do
  installparams="$installparams $dest"

  if [ "$(echo "$param" | cut -c 1)" != "-" ] ; then
    if ! [ -e "$param" ] ; then
      # Add ,ff8 if the source doesn't exist but it's there with ,ff8
      if [ -e "$param,ff8" ] ; then
        param="$param,ff8"
      fi
    fi

    # Don't install RISC OS binaries (only in non-packaging mode)
    if [ -z "$RO_PKG" ] && file $param | grep "RISC OS AIF executable" > /dev/null; then
      echo "RISC OS Cross installer: Not installing RISC OS binary"
      exit 0;
    fi
  fi

  dest=$param
done


# Check for ending up with no parameters
if [ -z "$installparams" ] ; then
  exit 0
fi


if [ -z "$RO_PKG" ] ; then
  # Regular Unix style install for cross environment
  exec $command $installparams $dest
else
  # Install for RISC OS headers, libraries and man pages

  if echo "$dest" | grep -E "/env/lib|/env/include|/env/bin" >/dev/null ; then
    dest=$(echo $dest | sed s#GCCSDK_ENV/#$AB_DIR/package/#)
    echo "RISC OS Cross installer: $installparams $dest"
    exec $command $installparams $dest
  fi

  if echo "$dest" | grep -E "/env/share/man/|/env/man/" >/dev/null ; then
    dest=$(echo $dest | sed -e "s#GCCSDK_ENV/share/#$AB_DIR/package/#" -e "s#GCCSDK_ENV/#$AB_DIR/package/#" -e "s#/man[0-9]##")
    # Skip option '-m'
    if [ "$(echo $installparams | cut -c -2)" == "-m" ] ; then
      installparams=$(echo $installparams | cut -f 3- -d ' ')
    fi

    # If there is only one source file and that equals the basename of destination, make
    # of the destination its dirname.
    if ! expr index "$installparams" ' ' ; then
      if [ "$(basename $installparams)" == "$(basename $dest)" ] ; then
        dest=$(dirname $dest)
      fi
    fi
    mkdir -p $dest
    for manpage in $installparams ; do
      rman -f HTML $manpage > $dest/`(basename $manpage)`,faf
    done
  fi
fi
