#!/bin/bash

# Binary install path

# The user can define GCCSDK_INSTALL_CROSSBIN to a directory
# containing an alternative cross compiler (e.g. for testing or
# developing purposes) than what GCCSDK has currently created at
# GCCSDK_BIN.
if [ -z "$GCCSDK_INSTALL_CROSSBIN" ] ; then
  export GCCSDK_INSTALL_CROSSBIN=GCCSDK_BIN
fi

# The user can define GCCSDK_INSTALL_ENV to a directory containing
# an alternative set of porting tools, cross compiled libraries or
# data files.
if [ -z "$GCCSDK_INSTALL_ENV" ] ; then
  export GCCSDK_INSTALL_ENV=GCCSDK_ENV
else
  if [ "$GCCSDK_INSTALL_ENV" != "GCCSDK_ENV" ] ; then
    echo "ro-path: environment variable GCCSDK_INSTALL_ENV has wrong value, expected GCCSDK_ENV while it seems to be $GCCSDK_INSTALL_ENV"
    exit 1
  fi
fi

# In order to be able to include header files using
# "#include <DeskLib:Wimp.h>" in the compiler:
export DESKLIB_PATH=GCCSDK_ENV/include/DeskLib

# We want to give the '--static' option to pkg-config by default.  Normally this
# should be possible to add this to PKG_CONFIG but some 'configure' scripts don't
# expect default arguments.
export PKG_CONFIG=GCCSDK_ENV/ro-pkg-config

PATH=$GCCSDK_INSTALL_CROSSBIN:GCCSDK_ENV/bin:$PATH "$@"
