#!/bin/bash

# Binary install path

export GCCSDK_INSTALL_CROSSBIN=GCCSDK_BIN
export GCCSDK_INSTALL_ENV=GCCSDK_ENV

# In order to be able to include header files using
# "#include <DeskLib:Wimp.h>" in the compiler:
export DESKLIB_PATH=GCCSDK_ENV/include/DeskLib

# We want to give the '--static' option to pkg-config by default.  Normally this
# should be possible to add this to PKG_CONFIG but some 'configure' scripts don't
# expect default arguments.
export PKG_CONFIG=GCCSDK_ENV/ro-pkg-config

PATH=$GCCSDK_INSTALL_CROSSBIN:GCCSDK_ENV/bin:$PATH "$@"
