#!/bin/bash

# Binary install path

export GCCSDK_INSTALL_CROSSBIN=GCCSDK_BIN
export GCCSDK_INSTALL_ENV=GCCSDK_ENV

if [ -z "$CC" ] ; then
  export CC=GCCSDK_ENV/arm-unknown-riscos-gcc
fi

if [ -z "$CXX" ] ; then
  export CXX=GCCSDK_ENV/arm-unknown-riscos-g++
fi

if [ -z "$ASASM" ] ; then
  export ASASM=GCCSDK_BIN/asasm
fi

# In order to be able to include header files using
# "#include <DeskLib:Wimp.h>" in the compiler:
export DESKLIB_PATH=GCCSDK_ENV/include/DeskLib

# Ensure we look at cross .pc files.
export PKG_CONFIG=GCCSDK_ENV/ro-pkg-config

PATH=$GCCSDK_INSTALL_CROSSBIN:GCCSDK_ENV:GCCSDK_ENV/bin:$PATH "$@"
