/*
 * Copyright (C) 1999-2000 Robin Watts/Justin Fletcher
 */

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#include "error.h"
#include "options.h"
#include "format.h"
#include "readfile.h" /* For fields */

#include "VersionNum" /* CVS maintained version numbers */

void WriteBlank(void) {

  FILE *file;
  field_t *field;

  if (!opt.blank)
    return;

  file=fopen(opt.infile,"r");
  if (file!=NULL)
    ErrorFatal("File %s already exists - not overwriting",opt.infile);

  printf("Generating blank CMHG template\n");

  file=fopen(opt.infile,"w");

  if (file==NULL)
    ErrorFatal("Cannot write blank template %s",opt.infile);

  format_wrap(file, "; ",
                    "; ",
"CMHG template, generated by CMunge " Module_FullVersionAndDate "\n"
"\n"
"Customise this to fit the module you are writing",
                    "\n\n");

  field=fields;

  while (field->name)
  {
    if (field->values.type != ft_alias)
    {
      if ( (opt.cmhg && (field->hgtype & IN_CMHG)) ||
           (!opt.cmhg && (field->hgtype & IN_CMUNGE)) )
      {
        format_wrap(file, "; ",
                          "; ", field->blank.comment,
                          "");
        fprintf(file,"%s: %s\n\n",field->name,field->blank.value);
      }
    }
    field++;
  }
  fclose(file);
  exit(EXIT_SUCCESS); /* And exit NOW because we can't do any more processing */
}
