/*
 * Copyright (C) 2000 Robin Watts/Justin Fletcher
 */

#include <stdio.h>
#include <string.h>

#include "gfile.h"
#include "error.h"
#include "options.h"
#include "comments.h"

#include "copyright.h"

#include "VersionNum" /* CVS maintained version file */

/* Define this to use X-variant SWIs in h files - not really useful */
/* #define USE_X_IN_HFILE */

static FILE *file;

static void hdr_swis(void) {

  swi_list l;
  char *prefix=opt.swi_names->name;
  int swi=opt.swi_base;

  /* Non-X variants */
  l = opt.swi_names;
  if (l)
    l = l->next;

  asm_comment(file, "SWI numbers");
  {
    int len=0;
    while (len++<24) fputc(' ',file);
    fprintf(file, "^ &%08x\n",swi);
  }

  while (l) {
    char *name=l->name;
    int startlen,len;
    startlen=len=strlen(prefix)+1+strlen(name)+1;
    fprintf(file, "%s_%s ", prefix, name);
    while (len++<24) fputc(' ',file);
    fprintf(file, "# 1\n");
    swi++;
    l=l->next;
  }

  /* X variants */
  swi=opt.swi_base;
  l = opt.swi_names;
  if (l)
    l = l->next;

  {
    int len=0;
    while (len++<24) fputc(' ',file);
    fprintf(file, "^ &%08x\n",swi+(1<<17));
  }

  while (l) {
    char *name=l->name;
    int startlen,len;
    startlen=len=1+strlen(prefix)+1+strlen(name)+1;
    fprintf(file, "X%s_%s ", prefix, name);
    while (len++<24) fputc(' ',file);
    fprintf(file, "# 1\n");
    swi++;
    l=l->next;
  }

}

static void h_swis(void) {

  swi_list l;
  char *prefix=opt.swi_names->name;
  int swi=opt.swi_base;

  /* Non-X variants */
  l = opt.swi_names;
  if (l)
    l = l->next;

  c_comment(file, "SWI numbers");

  while (l) {
    char *name=l->name;
    int startlen,len;
    startlen=len=strlen(prefix)+1+strlen(name)+1;
    fprintf(file, "#define %s_%s ", prefix, name);
    while (len++<24) fputc(' ',file);
    fprintf(file, "0x%x\n",swi);
    len=startlen+1;
#ifdef USE_X_IN_HFILE
    fprintf(file, "#define X%s_%s ", prefix, name);
    while (len++<24) fputc(' ',file);
    fprintf(file, "0x%x\n",0x20000+swi);
#endif
    swi++;
    l=l->next;
  }

  fprintf(file, "\n");

}

/* we output an assembler hdr file sometimes, so that we don't have
   to worry about anything nasty like inconsistant constructs; the only
   important ones here really are the SWI numbers which it is very useful
   to have in an exported hdr file */
void WriteExport_Hdr(void) {

  if (!opt.x_hdr)
    return;

  file = file_write(opt.x_hdr, remove_onfail);
  if (file == NULL)
    ErrorFatal("Couldn't create assembler SWI header file: %s", opt.x_hdr);

  asm_comment(file, "Generated by CMunge " Module_FullVersionAndDate "\n"
                    "CMunge " Copyright_CMunge );

  fprintf(file, "\n");

  if (opt.swi_handler || opt.swi_codesupplied)
    hdr_swis();

  fprintf(file, "\n\n\tEND\n");
  file_close(file);
}

/* we output a C SWI header file so that the SWI numbers are know
   elsewhere */
void WriteExport_H(void) {

  if (!opt.x_h)
    return;

  file = file_write(opt.x_h, remove_onfail);
  if (file == NULL)
    ErrorFatal("Couldn't create C SWI header file: %s", opt.x_hdr);

  c_comment(file, "Generated by CMunge " Module_FullVersionAndDate "\n"
                  "CMunge " Copyright_CMunge);

  fprintf(file, "\n");
  fprintf(file, "#ifndef %s_SWI_H\n",opt.title);
  fprintf(file, "#define %s_SWI_H\n\n",opt.title);

  if (opt.swi_handler || opt.swi_codesupplied)
    h_swis();

  fprintf(file, "#endif\n\n");
  file_close(file);
}
