#!/bin/bash
# Call the 'convert-unixlib.pl' script to convert AOF unixlib into an ELF libunixlib
# Written by John Tytgat
# Copyright (c) 2006 GCCSDK Developers

if [ -z "$GCCSDK_AOFUNIXLIB" ] ; then
  echo "\$GCCSDK_AOFUNIXLIB needs to be defined"
  exit 1
fi
if [ -z "$GCCSDK_SRCDIR" ] ; then
  echo "\$GCCSDK_SRCDIR needs to be defined"
  exit 1
fi
if [ ! -d $GCCSDK_AOFUNIXLIB ] ; then
  echo "\$GCCSDK_AOFUNIXLIB is wrongly defined"
  exit 1
fi

$GCCSDK_AOFUNIXLIB/elf/convert-unixlib.pl $GCCSDK_AOFUNIXLIB $GCCSDK_SRCDIR/libunixlib

# We don't want these headers in our GCC4 build (already provided by GCC itself):
test -f $GCCSDK_SRCDIR/libunixlib/include/float.h && rm  $GCCSDK_SRCDIR/libunixlib/include/float.h
test -f $GCCSDK_SRCDIR/libunixlib/include/stdarg.h && rm  $GCCSDK_SRCDIR/libunixlib/include/stdarg.h
test -f $GCCSDK_SRCDIR/libunixlib/include/stddef.h && rm  $GCCSDK_SRCDIR/libunixlib/include/stddef.h
test -f $GCCSDK_SRCDIR/libunixlib/include/varargs.h && rm  $GCCSDK_SRCDIR/libunixlib/include/varargs.h
