#!/bin/bash
# Call the 'convert-unixlib.pl' script to convert AOF unixlib into an ELF libunixlib
# Written by John Tytgat
# Copyright (c) 2006 GCCSDK Developers

if [ -z "$GCCSDK_AOFUNIXLIB" ] ; then
  echo "\$GCCSDK_AOFUNIXLIB needs to be defined"
  exit 1
fi
if [ -z "$GCCSDK_DIR" ] ; then
  echo "\$GCCSDK_DIR needs to be defined"
  exit 1
fi
if [ ! -d $GCCSDK_AOFUNIXLIB ] ; then
  echo "\$GCCSDK_AOFUNIXLIB is wrongly defined"
  exit 1
fi

$GCCSDK_AOFUNIXLIB/elf/convert-unixlib.pl $GCCSDK_AOFUNIXLIB $GCCSDK_DIR/libunixlib
