#define FFESTR_openlACCESS 6
#define FFESTR_openlACTION 6
#define FFESTR_openlASSOCIATEVARIABLE 17
#define FFESTR_openlBLANK 5
#define FFESTR_openlBLOCKSIZE 9
#define FFESTR_openlBUFFERCOUNT 11
#define FFESTR_openlCARRIAGECONTROL 15
#define FFESTR_openlDEFAULTFILE 11
#define FFESTR_openlDELIM 5
#define FFESTR_openlDISP 4
#define FFESTR_openlDISPOSE 7
#define FFESTR_openlERR 3
#define FFESTR_openlEXTENDSIZE 10
#define FFESTR_openlFILE 4
#define FFESTR_openlFORM 4
#define FFESTR_openlINITIALSIZE 11
#define FFESTR_openlIOSTAT 6
#define FFESTR_openlKEY 3
#define FFESTR_openlMAXREC 6
#define FFESTR_openlNAME 4
#define FFESTR_openlNOSPANBLOCKS 12
#define FFESTR_openlORGANIZATION 12
#define FFESTR_openlPAD 3
#define FFESTR_openlPOSITION 8
#define FFESTR_openlREADONLY 8
#define FFESTR_openlRECL 4
#define FFESTR_openlRECORDSIZE 10
#define FFESTR_openlRECORDTYPE 10
#define FFESTR_openlSHARED 6
#define FFESTR_openlSTATUS 6
#define FFESTR_openlTYPE 4
#define FFESTR_openlUNIT 4
#define FFESTR_openlUSEROPEN 8

enum ffestrOpen_
{
FFESTR_openNone,
FFESTR_openACCESS,
FFESTR_openACTION,
FFESTR_openASSOCIATEVARIABLE,
FFESTR_openBLANK,
FFESTR_openBLOCKSIZE,
FFESTR_openBUFFERCOUNT,
FFESTR_openCARRIAGECONTROL,
FFESTR_openDEFAULTFILE,
FFESTR_openDELIM,
FFESTR_openDISP,
FFESTR_openDISPOSE,
FFESTR_openERR,
FFESTR_openEXTENDSIZE,
FFESTR_openFILE,
FFESTR_openFORM,
FFESTR_openINITIALSIZE,
FFESTR_openIOSTAT,
FFESTR_openKEY,
FFESTR_openMAXREC,
FFESTR_openNAME,
FFESTR_openNOSPANBLOCKS,
FFESTR_openORGANIZATION,
FFESTR_openPAD,
FFESTR_openPOSITION,
FFESTR_openREADONLY,
FFESTR_openRECL,
FFESTR_openRECORDSIZE,
FFESTR_openRECORDTYPE,
FFESTR_openSHARED,
FFESTR_openSTATUS,
FFESTR_openTYPE,
FFESTR_openUNIT,
FFESTR_openUSEROPEN,
FFESTR_open
};
typedef enum ffestrOpen_ ffestrOpen;
