; Generated by gcc 2.95.2 19991024 (release) for ARM/RISC OS
__r0	RN	0
__a1	RN	0
__a2	RN	1
__a3	RN	2
__a4	RN	3
__v1	RN	4
__v2	RN	5
__v3	RN	6
__v4	RN	7
__v5	RN	8
__v6	RN	9
__sl	RN	10
__fp	RN	11
__ip	RN	12
__sp	RN	13
__lr	RN	14
__pc	RN	15
__f0	FN	0
__f1	FN	1
__f2	FN	2
__f3	FN	3
__f4	FN	4
__f5	FN	5
__f6	FN	6
__f7	FN	7
	AREA |C$$code1|, CODE, READONLY
|gcc2_compiled.|
	ALIGN
|LC..0|
	DCB &62, &00
	ALIGN
	EXPORT	|open|
|open|
	; args = 4, pretend = 12, frame = 48, alloca = 0
	; frame_needed = 1, anonymous_args = 1, regs_live[14] = 0
	; nonlocal_label = 0, nonlocal_goto = 0, clobbers lr = 1
	mov	__ip, __sp
	stmfd	__sp!, {__a2, __a3, __a4}
	stmfd	__sp!, {__v6, __fp, __ip, __lr, __pc}
	sub	__fp, __ip, #16
	cmp	__sp, __sl
	IMPORT	|__rt_stkovf_split_small|
	bllt	|__rt_stkovf_split_small|
	sub	__sp, __sp, #48
	mov	__v6, __sp
	str	__a1, [__v6, #0]
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #512
	cmp	__ip, #0
	beq	|L..3|
	add	__ip, __fp, #8
	str	__ip, [__v6, #4]
	ldr	__ip, [__v6, #4]
	add	__a3, __ip, #4
	str	__a3, [__v6, #4]
	mvn	__ip, #3
	ldr	__a3, [__v6, #4]
	add	__ip, __ip, __a3
	ldr	__a3, [__ip, #0]
	str	__a3, [__v6, #8]
	b	|L..4|
|L..3|
	ldr	__ip, |L..24|
	str	__ip, [__v6, #8]
|L..4|
	ldr	__a1, [__v6, #0]
	ldr	__a2, [__fp, #4]
	bl	|__uname|
	str	__a1, [__v6, #0]
	add	__ip, __v6, #20
	mov	__a1, #5
	ldr	__a2, [__v6, #0]
	mov	__a3, __ip
	bl	|os_file|
	mov	__ip, __a1
	str	__ip, [__v6, #44]
	ldr	__ip, [__v6, #44]
	cmp	__ip, #0
	beq	|L..5|
	ldr	__a1, [__v6, #44]
	bl	|__seterr|
	mvn	__a1, #0
	b	|L..2|
|L..5|
	ldr	__ip, [__v6, #20]
	cmp	__ip, #0
	beq	|L..6|
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #2560
	cmp	__ip, #2560
	bne	|L..7|
	ldr	__ip, |L..24|+4
	mov	__a3, #17
	str	__a3, [__ip, #0]
	mvn	__a1, #0
	b	|L..2|
|L..7|
	ldr	__ip, [__v6, #20]
	cmp	__ip, #2
	bne	|L..6|
	ldr	__ip, |L..24|+4
	mov	__a3, #21
	str	__a3, [__ip, #0]
	mvn	__a1, #0
	b	|L..2|
|L..8|
|L..6|
	mov	__ip, #0
	mov	__a3, __ip
	strb	__a3, [__v6, #17]
	mov	__ip, #0
	mov	__a3, __ip
	strb	__a3, [__v6, #18]
	mov	__ip, #0
	mov	__a3, __ip
	strb	__a3, [__v6, #19]
	ldr	__ip, [__fp, #4]
	cmp	__ip, #1
	beq	|L..11|
	cmp	__ip, #1
	bgt	|L..21|
	cmp	__ip, #0
	beq	|L..10|
	b	|L..19|
|L..21|
	cmp	__ip, #2
	beq	|L..14|
	b	|L..19|
|L..10|
	mov	__ip, #114
	mov	__a3, __ip
	strb	__a3, [__v6, #16]
	b	|L..9|
|L..11|
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #8
	cmp	__ip, #0
	beq	|L..12|
	mov	__ip, #97
	mov	__a3, __ip
	strb	__a3, [__v6, #17]
	b	|L..13|
|L..12|
	mov	__ip, #119
	mov	__a3, __ip
	strb	__a3, [__v6, #17]
|L..13|
	b	|L..9|
|L..14|
	mov	__ip, #43
	mov	__a3, __ip
	strb	__a3, [__v6, #17]
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #8
	cmp	__ip, #0
	beq	|L..15|
	mov	__ip, #97
	mov	__a3, __ip
	strb	__a3, [__v6, #16]
	b	|L..16|
|L..15|
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #1024
	cmp	__ip, #0
	beq	|L..17|
	mov	__ip, #119
	mov	__a3, __ip
	strb	__a3, [__v6, #16]
	b	|L..16|
|L..17|
	mov	__ip, #114
	mov	__a3, __ip
	strb	__a3, [__v6, #16]
|L..18|
|L..16|
	b	|L..9|
|L..19|
	ldr	__ip, |L..24|+4
	mov	__a3, #22
	str	__a3, [__ip, #0]
	mvn	__a1, #0
	b	|L..2|
|L..9|
	ldr	__a3, [__fp, #4]
	and	__ip, __a3, #8192
	cmp	__ip, #0
	beq	|L..22|
	add	__ip, __v6, #16
	mov	__a1, __ip
	ldr	__a2, |L..24|+8
	bl	|strcat|
|L..22|
	add	__ip, __v6, #16
	ldr	__a1, [__v6, #0]
	mov	__a2, __ip
	bl	|fopen|
	mov	__ip, __a1
	str	__ip, [__v6, #12]
	ldr	__ip, [__v6, #12]
	cmp	__ip, #0
	bne	|L..23|
	bl	|_kernel_last_oserror|
	mov	__ip, __a1
	mov	__a1, __ip
	bl	|__seterr|
	mvn	__a1, #0
	b	|L..2|
|L..23|
	ldr	__ip, [__v6, #12]
	ldr	__a3, [__ip, #52]
	mov	__a1, __a3
	b	|L..2|
|L..25|
	ALIGN
|L..24|
	DCD	511
	DCD	|errno|
	DCD	|LC..0|
|L..2|
	ldmea	__fp, {__v6, __fp, __sp, __pc}^
	IMPORT	|_kernel_last_oserror|
	IMPORT	|fopen|
	IMPORT	|strcat|
	IMPORT	|errno|
	IMPORT	|__seterr|
	IMPORT	|os_file|
	IMPORT	|__uname|
	IMPORT	|__builtin_next_arg|
	END
