#!/bin/bash
# Simple script to generate the Drlink edit file to hook in the dmalloc routines in UnixLib

# $1 = UnixLib library filename

set -e

if [ -z "$1" ] ; then
  echo $0": error: missing UnixLib library filename"
  exit 1
fi
if [ -z "$GCCSDK_INSTALL_CROSSBIN" ] ; then
  echo $0" : error: \$GCCSDK_INSTALL_CROSSBIN is not defined"
  exit 1
fi

# $1 = symbol to change
# $2 = AOF filename
aof_change()
{
  local SYMISEXTERN=`$GCCSDK_INSTALL_CROSSBIN/decaof -s $2 | grep -w $1 | grep -i "extern"`
  if [ ! -z "$SYMISEXTERN" ] ; then
    echo "change "$2"("$1",__unixlib_real_"$1")"
  fi
}

# $1 = symbol to change
lib_rename_and_change()
{
  local SYMBOL=$1

  for ANAOF in $ALLAOFS ; do
    local SYMISGLOBAL=`$GCCSDK_INSTALL_CROSSBIN/decaof -s $ANAOF | grep -w $SYMBOL | grep -i "global"`
    if [ ! -z "$SYMISGLOBAL" ] ; then
      echo "rename "$ANAOF"("$SYMBOL",__unixlib_real_"$SYMBOL")"
    fi
    aof_change $SYMBOL $ANAOF
  done
  echo
}

ALLAOFS=$($GCCSDK_INSTALL_CROSSBIN/libfile -l $1)

lib_rename_and_change "malloc"
lib_rename_and_change "realloc"
lib_rename_and_change "calloc"
lib_rename_and_change "strdup"
lib_rename_and_change "strndup"
lib_rename_and_change "free"
#lib_rename_and_change "recalloc"
lib_rename_and_change "memalign"
lib_rename_and_change "valloc"
lib_rename_and_change "cfree"

exit 0
