--- src/Makefile.in.orig	2009-08-24 21:08:09.000000000 -0700
+++ src/Makefile.in	2009-08-24 21:10:27.000000000 -0700
@@ -409,7 +409,7 @@
 LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
 CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
 	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
-CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
+CXXLINK = $(CXXLD) -all-static $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
 	-o $@
 SOURCES = $(libwesnoth_core_a_SOURCES) $(libwesnoth_a_SOURCES) \
 	$(campaignd_SOURCES) $(cutter_SOURCES) $(exploder_SOURCES) \
