--- src/global.cc.orig	2004-08-19 17:24:20.000000000 +0100
+++ src/global.cc	2014-02-28 11:13:58.000000000 +0000
@@ -317,64 +317,64 @@
 /////////////////////////////
 
 void initAllSurfaces() {
-  surfaceDB.loadSurface("./images/fighter.bmp" );
-  surfaceDB.loadSurface("./images/fighterShadow.bmp", true);
-  surfaceDB.loadSurface("./images/bomber.bmp");
-  surfaceDB.loadSurface("./images/bomberShadow.bmp", true);
-  surfaceDB.loadSurface("./images/tank.bmp");
-  surfaceDB.loadSurface("./images/boss1MainGun.bmp");
-  surfaceDB.loadSurface("./images/boss1RocketLauncher.bmp");
-  surfaceDB.loadSurface("./images/boss1ShotBatteryLeft.bmp");
-  surfaceDB.loadSurface("./images/boss1ShotBatteryRight.bmp");
-  surfaceDB.loadSurface("./images/wreckFighter.bmp");
-  surfaceDB.loadSurface("./images/wreckBomber.bmp");
-  surfaceDB.loadSurface("./images/wreckTank.bmp");
-  surfaceDB.loadSurface("./images/wreckBoss1.bmp");
-  surfaceDB.loadSurface("./images/wreckBossBackground.bmp");
-  surfaceDB.loadSurface("./images/boss.bmp");
-  surfaceDB.loadSurface("./images/normalShot.bmp");
-  surfaceDB.loadSurface("./images/heavyShot.bmp");
-  surfaceDB.loadSurface("./images/normalShotHF.bmp");
-  surfaceDB.loadSurface("./images/dumbfire.bmp");
-  surfaceDB.loadSurface("./images/kickAssRocket.bmp");
-  surfaceDB.loadSurface("./images/kickAssRocketShadow.bmp", true);
-  surfaceDB.loadSurface("./images/hellfire.bmp");
-  surfaceDB.loadSurface("./images/hellfireShadow.bmp", true);
-  surfaceDB.loadSurface("./images/machineGun.bmp");
-  surfaceDB.loadSurface("./images/energyBeam.bmp", true);
-  surfaceDB.loadSurface("./images/laser.bmp");
-  surfaceDB.loadSurface("./images/enemyShotNormal.bmp");
-  surfaceDB.loadSurface("./images/tankRocket.bmp");
-  surfaceDB.loadSurface("./images/tankRocketShadow.bmp", true);
-  surfaceDB.loadSurface("./images/heatseeker.bmp");
-  surfaceDB.loadSurface("./images/shotNuke.bmp");
-  surfaceDB.loadSurface("./images/shotNukeShadow.bmp", true);
-  surfaceDB.loadSurface("./images/nukeEffect.bmp");
-  surfaceDB.loadSurface("./images/sonic.bmp");
-  surfaceDB.loadSurface("./images/itemPrimaryUpgrade.bmp");
-  surfaceDB.loadSurface("./images/itemDumbfireDouble.bmp");
-  surfaceDB.loadSurface("./images/itemKickAssRocket.bmp");
-  surfaceDB.loadSurface("./images/itemHellfire.bmp");
-  surfaceDB.loadSurface("./images/itemMachineGun.bmp");
-  surfaceDB.loadSurface("./images/itemHealth.bmp");
-  surfaceDB.loadSurface("./images/itemHeatseeker.bmp");
-  surfaceDB.loadSurface("./images/itemNuke.bmp");
-  surfaceDB.loadSurface("./images/itemDeflector.bmp");
-  surfaceDB.loadSurface("./images/itemEnergyBeam.bmp");
-  surfaceDB.loadSurface("./images/itemLaser.bmp");
-  surfaceDB.loadSurface("./images/background.bmp");
-  surfaceDB.loadSurface("./images/lightFighterShieldDamaged.bmp");
-  surfaceDB.loadSurface("./images/heavyFighterShieldDamaged.bmp");
-  surfaceDB.loadSurface("./images/heavyFighterDeflector.bmp", true);
-  surfaceDB.loadSurface("./images/font-20red.bmp");
-  surfaceDB.loadSurface("./images/font-20blue.bmp");
-  surfaceDB.loadSurface("./images/explosion.bmp");
-  surfaceDB.loadSurface("./images/explosionEnemy.bmp");
-  surfaceDB.loadSurface("./images/bannerExcellent.bmp", true);
-  surfaceDB.loadSurface("./images/bannerYouRule.bmp", true);
-  surfaceDB.loadSurface("./images/bannerHeiho.bmp", true);
-  surfaceDB.loadSurface("./images/bannerHealth.bmp", true);
-  surfaceDB.loadSurface("./images/bannerEnemysKilled.bmp", true);
-  surfaceDB.loadSurface("./images/bannerBonus100.bmp", true);
-  surfaceDB.loadSurface("./images/bannerBonus200.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/fighter.bmp" );
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/fighterShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bomber.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bomberShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/tank.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/boss1MainGun.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/boss1RocketLauncher.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/boss1ShotBatteryLeft.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/boss1ShotBatteryRight.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/wreckFighter.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/wreckBomber.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/wreckTank.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/wreckBoss1.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/wreckBossBackground.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/boss.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/normalShot.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/heavyShot.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/normalShotHF.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/dumbfire.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/kickAssRocket.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/kickAssRocketShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/hellfire.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/hellfireShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/machineGun.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/energyBeam.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/laser.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/enemyShotNormal.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/tankRocket.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/tankRocketShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/heatseeker.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/shotNuke.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/shotNukeShadow.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/nukeEffect.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/sonic.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemPrimaryUpgrade.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemDumbfireDouble.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemKickAssRocket.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemHellfire.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemMachineGun.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemHealth.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemHeatseeker.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemNuke.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemDeflector.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemEnergyBeam.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/itemLaser.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/background.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/lightFighterShieldDamaged.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/heavyFighterShieldDamaged.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/heavyFighterDeflector.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/font-20red.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/font-20blue.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/explosion.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/explosionEnemy.bmp");
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerExcellent.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerYouRule.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerHeiho.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerHealth.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerEnemysKilled.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerBonus100.bmp", true);
+  surfaceDB.loadSurface("/<AlienBlaster$Dir>/images/bannerBonus200.bmp", true);
 }
