#!/bin/bash
# Written by John Tytgat <John.Tytgat@aaug.net>
# Copyright (c) 2006-2007 GCCSDK Developers

set -e

pushd `dirname $0` > /dev/null
GCCSDK_ROOT=`pwd`
popd > /dev/null
source $GCCSDK_ROOT/setup-gccsdk-params

TARGET=arm-unknown-riscos
GCCSDK_BUILDDIR=$GCCSDK_ROOT/$TARGET

if [ ! -d $GCCSDK_BUILDDIR ] ; then
  mkdir -p $GCCSDK_BUILDDIR
fi
if [ ! -d $PREFIX ] ; then
  mkdir -p $PREFIX
fi

cd $GCCSDK_BUILDDIR
# Notes:
#   1) --with-cross-host is needed to correctly find the target libraries in
#      .../cross/arm-unknown-riscos/lib instead of .../cross/lib.
$GCCSDK_SRCDIR/configure --prefix=$PREFIX --enable-threads=posix \
	--disable-nls \
	--target=$TARGET --enable-sjlj-exceptions=no \
	--disable-c-mbchar --enable-languages=c,c++ \
	--enable-checking=no --disable-libstdcxx-pch \
	--enable-c99 --enable-cmath \
	--with-cross-host \
	--without-pic --enable-shared=libunixlib,libgcc,libstdc++ --without-x --enable-libgcj \
	--enable-maintainer-mode

# When you want the host binaries with debug information:
#   make CFLAGS='-O0 -g' LIBCFLAGS='-O0 -g' LIBCXXFLAGS='-O0 -g' all
# When you want to have optimized ARM libraries:
#   make CFLAGS_FOR_TARGET="-O3 -march=armv5" CXXFLAGS_FOR_TARGET="-O3 -march=armv5" all
# When you have a multicore or multicpu machine, you might want to specify '-jx' with 'x'
# a suitable number (see 'man make') to speed up compilations.
make all
make install
