#!/bin/bash -e

function error_handler {
  echo ""
  echo "Looks like the build failed.  You might want to check out the README for what to do now."
  echo ""
  echo "If 'build-output.txt' exists, this will contain a record of the failure.  You can send the end of it to the
GCCSDK mailing list for help"
  echo "Once you fix the problem, you can simply run this script again."
  echo ""
  exit 1
}

trap error_handler ERR


GCCSDK_ROOT=`pwd`

for tool in \
  gcc make libtool automake-1.9 autogen patch makeinfo ; do

  if ! which $tool >/dev/null 2>&1 ; then
    echo "'$tool' couldn't be found.  This needs to be installed for GCCSDK".
    exit 1
  fi
done


. setup-gccsdk-params

if ! [ -e orig.gcc ] ; then
  ./download-gcc-binutils gcc
fi

if ! [ -e orig.binutils ] ; then
  ./download-gcc-binutils binutils
fi

./create-srcdir

./build-it 2>&1 | tee build-output.txt

./install-env

./riscos/built-it

echo "Built and installed GCCSDK ok.  Check out the README for examples of how to use the cross compiler or autobuilder"

