#!/bin/bash
# Written by John Tytgat <John.Tytgat@aaug.net>
# Copyright (c) 2006, 2007 GCCSDK Developers

# Arguments:
#  $1: file to patch (relative to $GCCSDK_SRCDIR)

set -e

pushd `dirname $0` > /dev/null
GCCSDK_ROOT=`pwd`
popd > /dev/null
source $GCCSDK_ROOT/setup-gccsdk-params

if [ "x"$1 == "x" ] ; then
  echo "Syntax: create-patch <file-in-gccsdk-dir-to-create-patch-from>"
  exit 1
fi
GCCSDK_PATCHFORFILE_REL=$1
GCCSDK_PATCHFORFILE_ABS=$GCCSDK_SRCDIR/$GCCSDK_PATCHFORFILE_REL

if [ ! -f $GCCSDK_PATCHFORFILE_ABS ] ; then
  echo "File $GCCSDK_PATCHFORFILE_ABS does not exist"
  exit 1
fi

# If we don't find the .orig version of the file of which we want to create
# a patch from, we search for the original file in the unchanged gcc / binutils
# distributions.
if [ ! -f $GCCSDK_PATCHFORFILE_ABS.orig ] ; then
  # Originial file does not exist, find it.
  if [ -f $GCCSDK_GCCORIG/$GCCSDK_PATCHFORFILE_REL ] ; then
    cp $GCCSDK_GCCORIG/$GCCSDK_PATCHFORFILE_REL $GCCSDK_PATCHFORFILE_ABS.orig
  elif [ -f $GCCSDK_BINUTILSORIG/$GCCSDK_PATCHFORFILE_REL ] ; then
    cp $GCCSDK_BINUTILSORIG/$GCCSDK_PATCHFORFILE_REL $GCCSDK_PATCHFORFILE_ABS.orig
  fi
fi

# If we find the original file in the gcc / binutils distribution, we make a patch.
if [ -f $GCCSDK_PATCHFORFILE_ABS.orig ] ; then
  GCCSDK_PATCHFILENAME=$GCCSDK_RECIPE_PATCHES/`echo $GCCSDK_PATCHFORFILE_REL | tr "/" "."`.p
  if [ ! -f $GCCSDK_PATCHFILENAME ] ; then
    echo Creating new patch $GCCSDK_PATCHFILENAME
  fi
  ( cd $GCCSDK_SRCDIR && diff -u $GCCSDK_PATCHFORFILE_REL.orig $GCCSDK_PATCHFORFILE_REL > $GCCSDK_PATCHFILENAME )
  echo "Patch $GCCSDK_PATCHFILENAME is (re)made."
  exit 0
fi

# Need to make a full copy in recipe/files directory ?
# We only do that we there is a previous version available.
if [ -f $GCCSDK_RECIPE_FILES/$GCCSDK_PATCHFORFILE_REL ] ; then
  cp $GCCSDK_PATCHFORFILE_ABS $GCCSDK_RECIPE_FILES/$GCCSDK_PATCHFORFILE_REL
  echo "Full copy $GCCSDK_RECIPE_FILES/$GCCSDK_PATCHFORFILE_REL made."
  exit 0
fi

echo Can\'t find original file $GCCSDK_PATCHFORFILE_REL to patch against it.
exit 1
