#!/bin/bash -e
# Written by John Tytgat <John.Tytgat@aaug.net>
# Copyright (c) 2007-2008 GCCSDK Developers
#
# Downloads the gcc or binutils sources needed to build GCCSDK.

pushd `dirname $0` > /dev/null
GCCSDK_ROOT=`pwd`
popd > /dev/null
source $GCCSDK_ROOT/setup-gccsdk-params

if [ "x"$1 != "xgcc" -a "x"$1 != "xbinutils" ] ; then
  echo "Syntax: download-gcc-binutils gcc | binutils [ version ]"
  exit 1
fi

if [ "x"$2 != "x" ] ; then
  if [ "x"$1 = "xgcc" ] ; then
    GCCSDK_SUPPORTED_GCC_RELEASE=$2
  else
    GCCSDK_SUPPORTED_BINUTILS_RELEASE=$2
  fi
fi

if [ "x"$1 = "xgcc" ] ; then
  if [ -d $GCCSDK_GCCORIG ] ; then
    echo "gcc already downloaded at $GCCSDK_GCCORIG ?"
    exit 1
  fi
  # Download gcc
  echo +++ Downloading gcc $GCCSDK_SUPPORTED_GCC_RELEASE
  wget -O $GCCSDK_GCCORIG-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/gcc/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE/gcc-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2 || (echo "Failed to download" && exit 1) || exit 1
  echo +++ Unpacking gcc $GCCSDK_SUPPORTED_GCC_RELEASE
  tar xjf $GCCSDK_GCCORIG-$GCCSDK_SUPPORTED_GCC_RELEASE.tar.bz2
  mv gcc-$GCCSDK_SUPPORTED_GCC_RELEASE $GCCSDK_GCCORIG

  # In case we want to take gcc from svn, we could incorporate the following in our script:
  #  $ svn co svn://gcc.gnu.org/svn/gcc/branches/gcc-4_1-branch $GCCSDK_GCCORIG
else
  if [ -d $GCCSDK_BINUTILSORIG ] ; then
    echo "binutils already downloaded at $GCCSDK_BINUTILSORIG ?"
    exit 1
  fi
  # Download binutils
  echo +++ Downloading binutils $GCCSDK_SUPPORTED_BINUTILS_RELEASE
  wget -O $GCCSDK_BINUTILSORIG-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 http://ftp.gnu.org/gnu/binutils/binutils-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2 || (echo "Failed to download" && exit 1) || exit 1
  echo +++ Unpacking binutils $GCCSDK_SUPPORTED_BINUTILS_RELEASE
  tar xjf $GCCSDK_BINUTILSORIG-$GCCSDK_SUPPORTED_BINUTILS_RELEASE.tar.bz2
  mv binutils-$GCCSDK_SUPPORTED_BINUTILS_RELEASE $GCCSDK_BINUTILSORIG

  # In case we want to take binutils from cvs, we could incorporate the following in our script:
  #  $ cvs -z9 -d:pserver:anoncvs@sourceware.org:/cvs/src login
  #     -> password: anoncvs
  #  $ cd `dirname $GCCSDK_BINUTILSORIG`
  #  $ cvs -z9 -d:pserver:anoncvs@sourceware.org:/cvs/src co -RPN -d tmp.binutils binutils
  #  $ mv tmp.binutils/src `basename $GCCSDK_BINUTILSORIG`
  #  $ rm -rf tmp.binutils
fi

echo Done.
