#!/bin/bash
# Written by John Tytgat <John.Tytgat@aaug.net>
# Copyright (c) 2006 GCCSDK Developers
#
# Makes links to GCCSDK 4.x cross-compiler binaries

set -e

pushd `dirname $0` > /dev/null
GCCSDK_ROOT=`pwd`
popd > /dev/null
source $GCCSDK_ROOT/setup-gccsdk-params

if [ -z "$GCCSDK_INSTALL_CROSSBIN" ] ; then
  echo \$GCCSDK_INSTALL_CROSSBIN is not defined
  exit 1
fi

cd $GCCSDK_INSTALL_CROSSBIN
# Remove all links:
find . -maxdepth 1 -type l | xargs rm -f
# Make links:
for f in `ls arm-unknown-riscos-*` ; do
  case "$f" in
    "arm-unknown-riscos-as" | "arm-unknown-riscos-ld")
       # Don't link as & ld to our cross-compiler version as otherwise
       # when using the host compiler, as & ld will be wrongly picked up.
       ;;
    *)
       ln -sf $f `echo $f | sed s/arm-unknown-riscos-//`
       ;;
  esac
done
