#!/bin/bash
# Written by John Tytgat <John.Tytgat@aaug.net>
# Copyright (c) 2006 GCCSDK Developers
#
# Script which can be run after building a GCCSDK 3.4.6 based cross-compiler
# when GCCSDK_INSTALL_CROSSBIN is shared with GCCSDK 4.x based build.  After
# running this script you can create links to gcc3.4.6 or gcc4.1 using
# make-links-gcc3 and make-links-gcc4.
# This script will no longer be necessary when GCCSDK 4.x is completely
# selfhostingand no longer need GCCSDK 3.4.6 to build any of the
# autobuilder projects.

set -e

pushd `dirname $0` > /dev/null
GCCSDK_ROOT=`pwd`
popd > /dev/null
source $GCCSDK_ROOT/setup-gccsdk-params

if [ -z "$GCCSDK_INSTALL_ENV" ] ; then
  echo \$GCCSDKk_INSTALL_ENV is not defined
  exit 1
fi
if [ -z "$GCCSDK_INSTALL_CROSSBIN" ] ; then
  echo \$GCCSDKk_INSTALL_CROSSBIN is not defined
  exit 1
fi

test -f $GCCSDK_INSTALL_CROSSBIN/ar && mv $GCCSDK_INSTALL_CROSSBIN/ar $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-ar
test -f $GCCSDK_INSTALL_CROSSBIN/g++ && mv $GCCSDK_INSTALL_CROSSBIN/g++ $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-g++
test -f $GCCSDK_INSTALL_CROSSBIN/g77 && mv $GCCSDK_INSTALL_CROSSBIN/g77 $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-g77
test -f $GCCSDK_INSTALL_CROSSBIN/gcc && mv $GCCSDK_INSTALL_CROSSBIN/gcc $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof/gcc
test -f $GCCSDK_INSTALL_CROSSBIN/gcov && mv $GCCSDK_INSTALL_CROSSBIN/gcov $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-gcov
test -f $GCCSDK_INSTALL_CROSSBIN/nm && mv $GCCSDK_INSTALL_CROSSBIN/nm $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-nm
test -f $GCCSDK_INSTALL_CROSSBIN/ranlib && mv $GCCSDK_INSTALL_CROSSBIN/ranlib $GCCSDK_INSTALL_CROSSBIN/arm-riscos-aof-ranlib
