#!/bin/bash -e

base=$(dirname $0)

if [ "$1" == '-h' ] ; then
  echo "Build or list status category of autobuilder packages"
  echo "Usage: $0 [opts] [category]"
  echo "        category = directory in autobuilder, default = libraries"
  echo "        opts = -h : Display this help"
  echo "               -l : List build status"
  echo "               -o : Check for possible non-optimized object compilation"
  echo "               -a : Try to build all, even if individual package fails"
  echo
  echo "examples:  List status of all packages in autobuilder:"
  echo "    $0 -l ."
  exit 0
fi


if [ "$1" == "-l" ] ; then
  list=true
  shift
else
  list=false
fi

if [ "$1" == "-a" ] ; then
  all=true
  shift
else
  all=false
fi

if [ "$1" == "-o" ] ; then
  opt=true
  shift
else
  opt=false
fi



subdir=$1

if [ -z "$subdir" ] ; then
  subdir=libraries
fi

function getnext() {
  local lib
  local name
  local num=0

  for lib in $(find $base/$subdir -type d) ; do
    if [ -e $lib/setvars ] ; then
      name=$(sed s#$base/## <<< $lib)

      if [ -s $lib/last-success ] || [ -e $lib/last-success -a "$list" = "false" ] ; then
        if $opt; then
          if grep -E -q "desklib|oslib" <<< $name ; then
            continue
          fi

          out=$(grep -E -- "-gcc|-g\+\+" $lib/last-success | grep -- -o | grep -v libtool | grep -v checking | grep -v -- -O2 | grep -v -- -O3 | grep -v -- -Os | \
              grep -v "\.so" | grep -v "unrecognized option" || true)
          if [ -n "$out" ] ; then
            echo "$name: $out"
          fi
        fi
      elif ! $opt; then

        if $list; then
          if [ -e $lib/last-depends ] ; then
            echo "$name: $(cat $lib/last-depends)"
          elif [ -e $lib/last-failure ] ; then
            if [ -e $lib/last-success ] ; then
              if [ -s "$lib/last-success" ] ; then
                echo "$name: (failed, earlier successful)"
              else
                echo "$name: (earlier failed, skipped)"
              fi
            else
              echo "$name: (failed)"
            fi
          elif [ -e $lib/last-success ] ; then
             echo "$name: (marked as successful, skipped)"
          else
            echo "$name: (not attempted)"
          fi
          num=$(($num + 1))

        else
          if $all && [ -e $lib/last-failure ] ; then
            continue
          fi

          basename $lib
          return 0
        fi
      fi
    fi
  done

  if $list && [ "$num" == 0 ] ; then
    echo "All packages in $subdir built ok"
  fi
}


if $list || $opt; then
  getnext
  exit 0
fi


lib=$(getnext)

while [ -n "$lib" ] ; do

  $base/build -v $lib

  lib=$(getnext)
done

echo "All libraries built"

