#!/bin/bash

AB_CVS_ROOT=$(grep AB_CVS_ROOT $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)
AB_CVS_MODULE=$(grep AB_CVS_MODULE $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)
AB_SVN=$(grep AB_SVN $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)
AB_URL=$(grep AB_URL $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)

if [ "$AB_CVS_ROOT" != "" ] ; then
  if [ "$AB_CVS_MODULE" == "" ] ; then
    echo "No CVS module specified"
    exit 1
  else
    cvs -d $AB_CVS_ROOT co $AB_CVS_MODULE
  fi

elif [ "$AB_SVN" != "" ] ; then
  svn co $AB_SVN

elif [ "$AB_URL" != "" ] ; then
  wget -nv $AB_URL
  base=$(basename $AB_URL)
  if echo $base | grep -q "\.gz$" ; then
    tar xfz $base
  elif echo $base | grep -q "\.bz2$" ; then
    tar xfj $base
  elif echo $base | grep -q "\.zip$" ; then
    unzip $base
  else
    echo "Unknown compression method"
    exit 1
  fi
else
  if [ -x /usr/bin/apt-get ] ; then
    apt-get source $AB_PACKAGE
  else
    # Slower method.  Fetch packages file ourself and parse it.
    debarchive=http://ftp.uk.debian.org/debian

    wget -nv $debarchive/dists/unstable/main/source/Sources.bz2
    bzgrep -A4 "/$AB_PACKAGE$" Sources.bz2 > files

    if ! [ -s files ] ; then
      echo "Package not found"
      exit 1
    fi

    debdir=$debarchive/$(grep Directory files | cut -d ' ' -f 2)
    wget -nv $debdir/$(grep \.orig\.tar\.gz files | cut -d ' ' -f 4)
    wget -nv $debdir/$(grep \.diff\.gz files | cut -d ' ' -f 4)

    tar xfz *.orig.tar.gz
    zcat *.diff.gz | patch -p0
  fi
fi


