#!/bin/bash

AB_CVS_ROOT=$(grep AB_CVS_ROOT $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)
AB_CVS_MODULE=$(grep AB_CVS_MODULE $AB_HOME/$AB_PACKAGEDIR/setvars | cut -d = -f 2)

if [ "$AB_CVS_ROOT" != "" ] ; then
  if [ "$AB_CVS_MODULE" == "" ] ; then
    echo "No CVS module specified"
    exit 1
  else
    cvs -d $AB_CVS_ROOT co $AB_CVS_MODULE
  fi
else
  if [ -x /usr/bin/apt-get ] ; then
    apt-get source $AB_PACKAGE
  else
    echo "Fetching source for this package requires apt-get"
    exit 1
  fi
fi


